### ISSUE TITLE
L key mapping incorrect

### ISSUE THREAD

**Issue by anirudhb** [ChrisMoller/aplwrap#1]
<del>Hello. I am learning APL, and I have gotten to lota (_Alt+l_), but the key is not rendering correctly. I believe this has something to do with the font? I request that you include UniFont, which includes all APL symbols.</del> It works. The problem is, when I look at the keymap (or press the combination) for the lota character (on the L key), it inserts another character.

**Comment by ChrisMoller** [comment]
unifont-7.0.01.ttf is already included in the aplwrap distribution. It 
should have been installed in
/usr/local/share/fonts (or wherever you set --prefix) and the font cache 
updated during installation.  FreeMono.ttf is the default font, but if 
you start aplwrap with either the -v or --vwdith flag you should get the 
unicode font.

Chris Moller

**Comment by anirudhb** [comment]
Whoops, sorry. Tested the lota character and it displays perfectly. I think maybe the problem is that the mapping is incorrect? Both _Alt+Shift+l_ and _Alt+l_ display with little boxes.

**Comment by anirudhb** [comment]
I just found out that _Alt+Shift+l_ is indeed mapping to the correct key.

**Comment by ChrisMoller** [comment]
alt-shift-i should be iota-underbar.

I use Avec.def from the apl distribution to map keys to APL characters.  
alt-i should be coming through as state 0x8, keycode 31 (keysym 0x69, 
i), which maps to iota, but that could be getting screwed up if you're 
using xmodmap or anything else that remaps keys.  Or, noticing your 
name, it just occurred to me: are you using something other than a US 
keyboard or a US locale?  That might change things too.  Anyway, you 
might try running xev and see what it says about alt-i.

-cm

**Comment by anirudhb** [comment]
I'm using a US keyboard and locale
